-- AlterTable
ALTER TABLE "clients" ADD COLUMN     "colorHex" TEXT NOT NULL DEFAULT '#3b82f6';

-- AlterTable
ALTER TABLE "deliverables" ALTER COLUMN "anio" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::int,
ALTER COLUMN "mes" SET DEFAULT EXTRACT(MONTH FROM CURRENT_DATE)::int;
