-- AlterTable
ALTER TABLE "client_billings" ADD COLUMN     "omitido" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "deliverables" ALTER COLUMN "anio" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::int,
ALTER COLUMN "mes" SET DEFAULT EXTRACT(MONTH FROM CURRENT_DATE)::int;
