-- AlterTable
ALTER TABLE "deliverables" ADD COLUMN     "copy" TEXT,
ALTER COLUMN "anio" SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::int,
ALTER COLUMN "mes" SET DEFAULT EXTRACT(MONTH FROM CURRENT_DATE)::int;
